#version 450

layout(location = 0) in vec4 in_aVec4;
layout(location = 1) in float in_aFloat;

layout(location = 0) out vec4 out_Color;
layout(location = 1) out float out_Depth;

void main()
{
    vec4 aVec4 = in_aVec4;
	float f = in_aFloat;
	
    out_Color = aVec4;
    out_Depth = 1.0;
}

/*
#version 140

//PIXEL SHADER
void main()
{
	//fragment shader inputs
	vec4 aVec4 = gl_FragCoord;
	//float frontFacing = gl_FrontFacing? 0:1;
	
	//fragment shader outputs
	gl_FragColor = aVec4;
	gl_FragDepth = 1.0;
	//gl_FragData[0] = vec4(0.0);  //can use either gl_FragColor or gl_FragData

	//pixel shader input
	//vec4 fragCoord = gl_FragCoord;
	//bool b = gl_FrontFacing;          //Unsupported builtin in HLSL: builtInFrontFacing
	//vec2 pointCoord = gl_PointCoord;  //Unsupported builtin in HLSL: builtInPointCoord
}*/

//=========================================================================
//Glslang: GLSL --> SPV conversion
//D:\Prgms\glslang\source\Test\semantics.glsl.frag -e main --keep-uncalled -V -H -o D:\Prgms\glslang\source\Test\semantics.glsl.frag.spv

//SPV outputs
/*
// Module Version 10000
// Generated by (magic number): 80001
// Id's are bound by 24

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 11 16 19 22
                              ExecutionMode 4 OriginUpperLeft
                              Source GLSL 450
                              Name 4  "main"
                              Name 9  "aVec4"
                              Name 11  "in_aVec4"
                              Name 14  "f"
                              Name 16  "in_aFloat"
                              Name 19  "out_Color"
                              Name 22  "out_Depth"
                              Decorate 11(in_aVec4) Location 0
                              Decorate 16(in_aFloat) Location 1
                              Decorate 19(out_Color) Location 0
                              Decorate 22(out_Depth) Location 1
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Function 7(fvec4)
              10:             TypePointer Input 7(fvec4)
    11(in_aVec4):     10(ptr) Variable Input
              13:             TypePointer Function 6(float)
              15:             TypePointer Input 6(float)
   16(in_aFloat):     15(ptr) Variable Input
              18:             TypePointer Output 7(fvec4)
   19(out_Color):     18(ptr) Variable Output
              21:             TypePointer Output 6(float)
   22(out_Depth):     21(ptr) Variable Output
              23:    6(float) Constant 1065353216
         4(main):           2 Function None 3
               5:             Label
        9(aVec4):      8(ptr) Variable Function
           14(f):     13(ptr) Variable Function
              12:    7(fvec4) Load 11(in_aVec4)
                              Store 9(aVec4) 12
              17:    6(float) Load 16(in_aFloat)
                              Store 14(f) 17
              20:    7(fvec4) Load 9(aVec4)
                              Store 19(out_Color) 20
                              Store 22(out_Depth) 23
                              Return
                              FunctionEnd
*/

//=========================================================================
//SPIRV-Cross: SPV --> GLSL
//--output D:\Prgms\glslang\source\Test\xksl\outputs\semantics.glsl.output.glsl D:\Prgms\glslang\source\Test\semantics.glsl.frag.spv
/*

#version 450

layout(location = 0) in vec4 in_aVec4;
layout(location = 1) in float in_aFloat;
layout(location = 0) out vec4 out_Color;
layout(location = 1) out float out_Depth;

void main()
{
    vec4 aVec4 = in_aVec4;
    float f = in_aFloat;
    out_Color = aVec4;
    out_Depth = 1.0;
}

*/

//=========================================================================
//SPIRV-Cross: SPV --> HLSL
//--hlsl --output D:\Prgms\glslang\source\Test\xksl\outputs\semantics.glsl.output.hlsl D:\Prgms\glslang\source\Test\semantics.glsl.frag.spv
/*

static float4 in_aVec4;
static float in_aFloat;
static float4 out_Color;
static float out_Depth;

struct SPIRV_Cross_Input
{
    float4 in_aVec4 : TEXCOORD0;
    float in_aFloat : TEXCOORD1;
};

struct SPIRV_Cross_Output
{
    float4 out_Color : COLOR0;
    float out_Depth : COLOR1;
};

void frag_main()
{
    float4 aVec4 = in_aVec4;
    float f = in_aFloat;
    out_Color = aVec4;
    out_Depth = 1.0f;
}

SPIRV_Cross_Output main(SPIRV_Cross_Input stage_input)
{
    in_aVec4 = stage_input.in_aVec4;
    in_aFloat = stage_input.in_aFloat;
    frag_main();
    SPIRV_Cross_Output stage_output;
    stage_output.out_Color = out_Color;
    stage_output.out_Depth = out_Depth;
    return stage_output;
}




*/